# Generated by Django 3.0 on 2020-12-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_negotiation_after_obe'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_rules',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
