# Generated by Django 3.0 on 2020-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_auction_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctiontyperanking',
            name='warning_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctiontypesealedbid',
            name='warning_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auctiontypetrafficlight',
            name='warning_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
