# Generated by Django 3.0 on 2020-12-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201215_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
