# Generated by Django 3.0 on 2021-09-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0032_delete_rfxautonego'),
        ('auctions', '0005_auctionitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='rfx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_rfxs', to='rfx.RFXData'),
        ),
    ]
