# Generated by Django 3.0 on 2024-08-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0017_voucher_vouchertranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.BooleanField(default=False)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_city', to='master_data.CountryState')),
                ('pick_up_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_city', to='master_data.CountryState')),
            ],
            options={
                'db_table': 'delivery_shipping_fee',
            },
        ),
    ]
