# Generated by Django 3.0 on 2024-10-17 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0021_delete_group'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('long_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('tax', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'delivery_transporter_list',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_code', models.CharField(max_length=6, unique=True)),
                ('member', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_student',
            },
        ),
        migrations.CreateModel(
            name='DeliveryResponsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('city_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_code', to='master_data.CountryState')),
                ('transporter_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_code', to='delivery.TransporterList')),
            ],
            options={
                'db_table': 'delivery_delivery_responsible',
            },
        ),
    ]
