# Generated by Django 3.0 on 2024-10-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryresponsible_transporterlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('de_tai', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'giangvien',
            },
        ),
    ]
