# Generated by Django 3.0 on 2024-11-12 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0003_auto_20241031_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeHoachDoAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_sinh_vien', models.IntegerField()),
                ('sl_do_an', models.IntegerField()),
                ('ky_mo', models.CharField(max_length=50)),
                ('tgbd_do_an', models.DateField()),
                ('tgkt_do_an', models.DateField()),
                ('tgbd_tao_do_an', models.DateField()),
                ('tgkt_tao_do_an', models.DateField()),
                ('tgbd_dang_ky_de_tai', models.DateField()),
                ('tgkt_dang_ky_de_tai', models.DateField()),
                ('tgbd_lam_do_an', models.DateField()),
                ('tgkt_lam_do_an', models.DateField()),
                ('tgbd_cham_phan_bien', models.DateField()),
                ('tgkt_cham_phan_bien', models.DateField()),
                ('tgbd_cham_hoi_dong', models.DateField()),
                ('tgkt_cham_hoi_dong', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ke_hoach_do_an', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kehoach_doan',
            },
        ),
    ]
