# Generated by Django 3.0 on 2024-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_giangvien'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQLDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=255)),
                ('de_tai', models.CharField(max_length=1024)),
                ('giang_viens', models.ManyToManyField(related_name='groups', to='delivery.GiangVien')),
            ],
            options={
                'db_table': 'group_Qlda',
            },
        ),
    ]
