# Generated by Django 3.0 on 2024-11-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_kehoachdoan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detai',
            old_name='giang_vien',
            new_name='giangvien_id',
        ),
        migrations.AddField(
            model_name='detai',
            name='kehoachdoan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.KeHoachDoAn'),
        ),
    ]
