# Generated by Django 3.0 on 2024-10-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_groupqlda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupqlda',
            name='de_tai',
        ),
    ]
