# Generated by Django 3.0 on 2024-11-14 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_auto_20241113_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detai',
            name='giangvien_id',
        ),
        migrations.RemoveField(
            model_name='detai',
            name='kehoachdoan_id',
        ),
        migrations.RemoveField(
            model_name='detai',
            name='mo_ta',
        ),
        migrations.RemoveField(
            model_name='detai',
            name='ten_de_tai',
        ),
        migrations.AddField(
            model_name='detai',
            name='chuyennganh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detai',
            name='idgvhuongdan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huongdan_detai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detai',
            name='idgvphanbien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phanbien_detai', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detai',
            name='idkehoach',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.KeHoachDoAn'),
        ),
        migrations.AddField(
            model_name='detai',
            name='idnhom',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detai',
            name='madoan',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='detai',
            name='mota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detai',
            name='tendoan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detai',
            name='trangthai',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detai',
            name='yeucau',
            field=models.TextField(blank=True, null=True),
        ),
    ]
