# Generated by Django 3.0 on 2024-10-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_remove_groupqlda_de_tai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupQLDA',
        ),
    ]
