# Generated by Django 3.0 on 2024-11-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20241114_2340'),
        ('delivery', '0006_auto_20241114_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detai',
            name='idgvhuongdan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huongdan_detai', to='users.Admin'),
        ),
        migrations.AlterField(
            model_name='detai',
            name='idgvphanbien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phanbien_detai', to='users.Admin'),
        ),
    ]
