# Generated by Django 3.0 on 2024-10-24 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0006_delete_groupqlda'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupQLDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('de_tai', models.CharField(max_length=1024)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='delivery.GiangVien')),
                ('members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_qlda',
            },
        ),
    ]
