# Generated by Django 3.0 on 2024-11-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20241114_2340'),
        ('delivery', '0007_auto_20241115_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehoachdoan',
            name='user',
        ),
        migrations.AddField(
            model_name='kehoachdoan',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ke_hoach_do_an', to='users.Admin'),
        ),
    ]
