# Generated by Django 3.0 on 2024-10-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_groupqlda'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupqlda',
            name='ma_nhom',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='groupqlda',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
