# Generated by Django 3.0 on 2024-10-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20241024_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupqlda',
            old_name='ma_nhom',
            new_name='ma_Nhom',
        ),
    ]
