# Generated by Django 3.0 on 2024-11-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20241115_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kehoachdoan',
            name='admin',
        ),
    ]
