# Generated by Django 3.0 on 2024-11-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_remove_groupqlda_creator_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupqlda',
            name='max_member',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
