# Generated by Django 3.0 on 2024-10-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20241025_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupqlda',
            name='members',
        ),
    ]
