# Generated by Django 3.0 on 2024-11-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_groupqlda_max_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detai',
            name='idnhom',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
