# Generated by Django 3.0 on 2024-11-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_auto_20241115_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupqlda',
            name='creator_short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupqlda',
            name='de_tai',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
