# Generated by Django 3.0 on 2024-10-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_remove_groupqlda_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupqlda',
            name='giang_vien',
        ),
    ]
