# Generated by Django 3.0 on 2024-12-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20241121_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detai',
            name='idnhom',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
