# Generated by Django 3.0 on 2024-10-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0011_remove_groupqlda_giang_vien'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeTai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_de_tai', models.CharField(max_length=255)),
                ('mo_ta', models.TextField()),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detai',
            },
        ),
        migrations.DeleteModel(
            name='GiangVien',
        ),
    ]
