# Generated by Django 3.0 on 2024-11-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20241116_1715'),
        ('delivery', '0012_groupqlda_leader_user'),
    ]

    operations = [
    ]
