# Generated by Django 3.0 on 2024-12-06 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20241201_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'Invite'), (2, 'Join Request')], default=2),
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_huongdan', models.FloatField(default=0.0)),
                ('diem_phanbien', models.FloatField(default=0.0)),
                ('detai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='delivery.DeTai')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='delivery.GroupQLDA')),
            ],
            options={
                'db_table': 'grading',
            },
        ),
    ]
