# Generated by Django 3.0 on 2024-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_joingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupqlda',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
