# Generated by Django 3.0 on 2024-12-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_huongdan', models.FloatField(default=0.0)),
                ('diem_phanbien', models.FloatField(default=0.0)),
                ('detai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='delivery.DeTai')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradings', to='delivery.GroupQLDA')),
            ],
            options={
                'db_table': 'grading',
            },
        ),
    ]
