# Generated by Django 3.0 on 2024-12-08 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_auto_20241206_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grading',
            name='group',
        ),
    ]
