# Generated by Django 3.0 on 2024-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_remove_grading_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='diem_huongdan',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='grading',
            name='diem_phanbien',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
