# Generated by Django 3.0 on 2024-10-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20241029_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='join_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='delivery.JoinGroup'),
        ),
    ]
