# Generated by Django 3.0 on 2024-10-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_joinrequest_join_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='join_group',
        ),
    ]
