# Generated by Django 3.0 on 2024-10-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_remove_joinrequest_join_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='leader_join_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
