# Generated by Django 3.0 on 2024-10-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_joinrequest_leader_join_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinrequest',
            old_name='leader_join_group_id',
            new_name='leader_user_id',
        ),
    ]
