# Generated by Django 3.0 on 2021-05-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userdiamondsponsorfee'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyonepay',
            name='diamond_sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserDiamondSponsor'),
        ),
        migrations.CreateModel(
            name='UserDiamondSponsorPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_amount', models.FloatField()),
                ('method_payment', models.IntegerField(null=True)),
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_diamond_sponsor_payment', to='payment.History')),
                ('user_diamond_sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diamond_sponsor_payment', to='users.UserDiamondSponsor')),
            ],
            options={
                'db_table': 'payment_user_diamond_sponsor',
            },
        ),
    ]
