# Generated by Django 3.0 on 2024-09-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_delete_orderpaymentdetails'),
        ('payment', '0003_banktransfer_diamond_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AddField(
            model_name='historyonepay',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
