# Generated by Django 3.0 on 2021-02-23 03:30

import apps.sale_schema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=apps.sale_schema.models.our_partner_directory_path)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sale_schema_our_partner',
            },
        ),
    ]
