# Generated by Django 3.0 on 2023-03-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_schema', '0004_auto_20230216_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefeaturessupplier',
            name='product',
            field=models.IntegerField(default=1),
        ),
    ]
