# Generated by Django 3.0 on 2023-05-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_schema', '0005_profilefeaturessupplier_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpartner',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
