# Generated by Django 2.2.5 on 2020-12-04 03:16

import apps.user_guide.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale_schema', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, upload_to=apps.user_guide.models.video_directory_path)),
                ('status', models.BooleanField(default=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'buyer'), (3, 'supplier')], default=1)),
            ],
            options={
                'db_table': 'user_guide_coures',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'buyer'), (3, 'supplier')], default=1)),
            ],
            options={
                'db_table': 'user_guide_modules',
            },
        ),
        migrations.CreateModel(
            name='CoursesProfileFeaturesSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_guide.Courses')),
                ('profile_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_schema.ProfileFeaturesSupplier')),
            ],
            options={
                'db_table': 'user_guide_coures_profile_features_supplier',
            },
        ),
        migrations.CreateModel(
            name='CoursesProfileFeaturesBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_guide.Courses')),
                ('profile_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale_schema.ProfileFeaturesBuyer')),
            ],
            options={
                'db_table': 'user_guide_coures_profile_features_buyer',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_guide.Modules'),
        ),
    ]
