# Generated by Django 2.2.5 on 2020-12-04 03:15

import apps.master_data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_auction_type',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=128, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_data_bank',
            },
        ),
        migrations.CreateModel(
            name='ClientFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_client_focus',
            },
        ),
        migrations.CreateModel(
            name='ClusterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_cluster_code',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_contract_type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_country',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_program', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('commission', models.FloatField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_coupon',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_currency',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_delivery_term',
            },
        ),
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_data_email_list',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=25, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2000)),
                ('variables', models.TextField(max_length=2000, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_data_email_templates',
            },
        ),
        migrations.CreateModel(
            name='FamilyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_family_code',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_gender',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_industry',
            },
        ),
        migrations.CreateModel(
            name='IndustryCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True, null=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industryCluster', to='master_data.Industry')),
            ],
            options={
                'db_table': 'master_data_industry_cluster',
            },
        ),
        migrations.CreateModel(
            name='IndustrySectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True, null=True)),
                ('industry_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrySectors', to='master_data.IndustryCluster')),
            ],
            options={
                'db_table': 'master_data_industry_sectors',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_language',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_level',
            },
        ),
        migrations.CreateModel(
            name='NumberofEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_number_of_employee',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_payment_term',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_position',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2048)),
                ('discount', models.FloatField()),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_promotion',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_reason',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=apps.master_data.models.sponsor_logo_directory_path)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_sponsor',
            },
        ),
        migrations.CreateModel(
            name='SupplierList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_data_supplier_list',
            },
        ),
        migrations.CreateModel(
            name='TechnicalWeighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_technical_weighting',
            },
        ),
        migrations.CreateModel(
            name='UnitofMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('status', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'master_data_unit_of_measure',
            },
        ),
        migrations.CreateModel(
            name='SubClusterCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
                ('cluster_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subClusterCode', to='master_data.ClusterCode')),
            ],
            options={
                'db_table': 'master_data_sub_cluster_code',
            },
        ),
        migrations.CreateModel(
            name='IndustrySubSectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True, null=True)),
                ('industry_sectors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrySubSectors', to='master_data.IndustrySectors')),
            ],
            options={
                'db_table': 'master_data_industry_sub_sectors',
            },
        ),
        migrations.AddField(
            model_name='clustercode',
            name='family_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusterCode', to='master_data.FamilyCode'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, null=True)),
                ('sub_cluster_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='master_data.SubClusterCode')),
            ],
            options={
                'db_table': 'master_data_category',
            },
        ),
    ]
