# Generated by Django 3.0 on 2020-12-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_auctiontypetranslation_categorytranslation_clientfocustranslation_clustercodetranslation_contracttyp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplatestranslation',
            old_name='name',
            new_name='title',
        ),
    ]
