# Generated by Django 3.0 on 2020-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_auto_20201230_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplatestranslation',
            name='content',
            field=models.TextField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
