# Generated by Django 3.0 on 2021-03-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_emailtemplatestranslation_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measures_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=128, unique=True)),
                ('exchange_rate', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_data_exchange_rate',
            },
        ),
    ]
