# Generated by Django 3.0 on 2021-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='apply_for_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotion',
            name='apply_for_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
