# Generated by Django 3.0 on 2021-06-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_auto_20210401_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='user_given',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
