# Generated by Django 3.0 on 2021-06-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_auto_20210602_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='user_given_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
