# Generated by Django 3.0 on 2021-06-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_promotion_user_given_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='user_given',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='user_given_email',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='user_used',
        ),
        migrations.CreateModel(
            name='PromotionUserUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_given', models.CharField(blank=True, max_length=100, null=True)),
                ('user_used', models.CharField(blank=True, max_length=100, null=True)),
                ('user_given_email', models.CharField(blank=True, max_length=50, null=True)),
                ('user_used_email', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_users', to='master_data.Promotion')),
            ],
            options={
                'db_table': 'master_data_promotion_user_used',
            },
        ),
    ]
