# Generated by Django 3.0 on 2021-06-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_auto_20210607_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionuserused',
            name='user_given',
        ),
        migrations.RemoveField(
            model_name='promotionuserused',
            name='user_given_email',
        ),
        migrations.AddField(
            model_name='promotion',
            name='user_given',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='user_given_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
