# Generated by Django 3.0 on 2021-06-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_auto_20210608_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionuserused',
            name='amount_after_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionuserused',
            name='date_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionuserused',
            name='real_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotionuserused',
            name='title',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='promotionuserused',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
