# Generated by Django 3.0 on 2021-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_auto_20210609_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
