# Generated by Django 3.0 on 2023-03-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_promotion_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='apply_scope',
            field=models.CharField(blank=True, choices=[('for_buyer', 'For_buyer'), ('for_supplier_all_scope', 'For_supplier_all_scope'), ('for_supplier_profile_features', 'For_supplier_profile_features'), ('for_supplier_sicp', 'For_supplier_sicp'), ('for_supplier', 'For_supplier')], max_length=32, null=True),
        ),
    ]
