# Generated by Django 3.1.5 on 2023-10-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_countrystate_countrystatetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='apply_for_advertisement',
            field=models.BooleanField(default=False),
        ),
    ]
