# Generated by Django 3.0 on 2024-08-11 09:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_promotion_apply_for_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('label', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'master_data_voucher',
            },
        ),
        migrations.CreateModel(
            name='VoucherTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='master_data.Voucher')),
            ],
            options={
                'db_table': 'master_data_voucher_translation',
                'unique_together': {('language_code', 'voucher')},
            },
        ),
    ]
