# Generated by Django 3.0 on 2024-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_buyerclubvoucher_buyerclubvouchertranslation_setproductadvertisement_setproductadvertisementtranslat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setproductadvertisement',
            name='serviceFee',
            field=models.FloatField(null=True),
        ),
    ]
