# Generated by Django 3.0 on 2024-10-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
