# Generated by Django 3.0 on 2020-12-11 07:15

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSubAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('picture', models.ImageField(null=True, upload_to=apps.users.models.picture_directory_path)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.Currency')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Gender')),
                ('language', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.Language')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.Position')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='users.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sub_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_supplier_sub_account',
            },
        ),
        migrations.CreateModel(
            name='SupplierSubAccountActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField(auto_now_add=True)),
                ('reason_manual', models.CharField(max_length=256, null=True)),
                ('changed_state', models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'deactive')])),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier_sub_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sub_accounts_activity', to='users.SupplierSubAccount')),
            ],
            options={
                'db_table': 'users_supplier_sub_account_activity',
            },
        ),
    ]
