# Generated by Django 3.0 on 2021-01-05 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_suppliersubaccount_suppliersubaccountactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_established_since',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
