# Generated by Django 3.0 on 2021-02-25 09:10

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiamondSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_local', models.PositiveSmallIntegerField(choices=[(1, 'Postion_1'), (2, 'Postion_2'), (3, 'Postion_3'), (4, 'Postion_4'), (5, 'Postion_5'), (6, 'Postion_6'), (7, 'Postion_7'), (8, 'Postion_8'), (9, 'Postion_9'), (10, 'Postion_10')])),
                ('image', models.ImageField(upload_to=apps.users.models.diamond_sponsor_directory_path)),
                ('description', models.CharField(max_length=255, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'inactive'), (3, 'pending'), (4, 'cancelled')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diamond_sponsors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_user_diamond_sponsor',
            },
        ),
    ]
