# Generated by Django 3.0 on 2021-04-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdiamondsponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiamondsponsor',
            name='position_local',
        ),
        migrations.AlterField(
            model_name='userdiamondsponsor',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'active'), (2, 'inactive')]),
        ),
    ]
