# Generated by Django 3.0 on 2021-04-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210401_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
