# Generated by Django 3.0 on 2021-04-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userdiamondsponsor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
