# Generated by Django 3.0 on 2021-04-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userdiamondsponsor_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdiamondsponsor',
            name='is_confirmed',
        ),
    ]
