# Generated by Django 3.0 on 2021-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_userdiamondsponsor_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='is_confirmed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'approved'), (2, 'waiting'), (3, 'reject')], default=1),
            preserve_default=False,
        ),
    ]
