# Generated by Django 3.0 on 2021-04-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdiamondsponsor_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierflashsale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierflashsale',
            name='is_confirmed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'approved'), (2, 'waiting'), (3, 'rejected')], default=2),
        ),
    ]
