# Generated by Django 3.0 on 2021-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210414_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierflashsale',
            name='re_order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
