# Generated by Django 3.0 on 2021-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_supplierflashsale_re_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierflashsale',
            name='text_editer',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
