# Generated by Django 3.0 on 2021-04-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_supplierflashsale_text_editer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='text_editer',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
