# Generated by Django 3.0 on 2021-05-11 11:09

import apps.users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userdiamondsponsor_text_editer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSICP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_check', models.CharField(max_length=255, null=True)),
                ('is_confirmed', models.PositiveSmallIntegerField(choices=[(1, 'certified'), (2, 'waiting'), (3, 'failed')])),
                ('is_reviewed', models.PositiveSmallIntegerField(choices=[(1, 'reviewed'), (2, 'waiting review')])),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sicps', to='users.Supplier')),
            ],
            options={
                'db_table': 'supplier_sicp',
            },
        ),
        migrations.CreateModel(
            name='SupplierSICPFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to=apps.users.models.sicp_file_path)),
                ('sicp_type', models.PositiveSmallIntegerField(choices=[(1, 'legal_status'), (2, 'bank_account'), (3, 'certification_management'), (4, 'due_diligence'), (5, 'financial_risk_management'), (6, 'document_internal'), (7, 'document_external')])),
                ('ordered', models.IntegerField(null=True)),
                ('sicp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicp_files', to='users.SupplierSICP')),
            ],
            options={
                'db_table': 'supplier_sicp_files',
            },
        ),
    ]
