# Generated by Django 3.0 on 2021-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_suppliersicp_suppliersicpfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersicpfile',
            name='user_or_admin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'admin_internal_document'), (3, 'admin_external_document')], null=True),
        ),
    ]
