# Generated by Django 3.0 on 2021-05-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_suppliersicpfile_user_or_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersicp',
            name='text_editer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
