# Generated by Django 3.0 on 2021-05-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210518_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='SICPTextEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_editer', models.CharField(blank=True, max_length=10000, null=True)),
                ('sicp_type', models.PositiveSmallIntegerField(choices=[(1, 'bank_account'), (2, 'certification_management'), (3, 'due_diligence'), (4, 'financial_risk_management'), (5, 'legal_status'), (6, 'document_internal'), (7, 'document_external')])),
            ],
            options={
                'db_table': 'supplier_sicp_text_editor',
            },
        ),
        migrations.RemoveField(
            model_name='suppliersicp',
            name='text_editer',
        ),
    ]
