# Generated by Django 3.0 on 2021-05-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_supplierflashsale_link_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierflashsale',
            old_name='link_path',
            new_name='url_path',
        ),
    ]
