# Generated by Django 3.0 on 2021-05-21 07:18

import apps.users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_sicptexteditor_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sicptexteditor',
            name='files',
        ),
        migrations.CreateModel(
            name='SICPTextEditorFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(blank=True, null=True, upload_to=apps.users.models.sicp_text_editor_file_path)),
                ('sicp_text_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicp_text_editor', to='users.SICPTextEditor')),
            ],
            options={
                'db_table': 'supplier_sicp_text_editor_file',
            },
        ),
    ]
