# Generated by Django 3.0 on 2021-05-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210521_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicptexteditorfile',
            name='sicp_text_editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicp_text_editor_files', to='users.SICPTextEditor'),
        ),
    ]
