# Generated by Django 3.0 on 2021-05-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210521_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sicptexteditor',
            old_name='text_editer',
            new_name='text_editer_en',
        ),
        migrations.AddField(
            model_name='sicptexteditor',
            name='text_editer_vi',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
