# Generated by Django 3.0 on 2021-05-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210524_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicptexteditorfile',
            name='file_version',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'English'), (2, 'Vietnamese')], null=True),
        ),
    ]
