# Generated by Django 3.0 on 2021-05-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_sicptexteditorfile_file_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiamondSponsorFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fee', models.FloatField()),
            ],
            options={
                'db_table': 'users_user_diamond_sponsor_fee',
            },
        ),
    ]
