# Generated by Django 3.0 on 2021-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_userdiamondsponsorfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
