# Generated by Django 3.0 on 2021-06-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_supplier_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicptexteditor',
            name='sicp_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bank_account'), (2, 'certification_management'), (3, 'due_diligence'), (4, 'financial_risk_management'), (5, 'legal_status'), (6, 'document_internal'), (7, 'document_external'), (8, 'sanction_check')]),
        ),
        migrations.AlterField(
            model_name='suppliersicpfile',
            name='sicp_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'bank_account'), (2, 'certification_management'), (3, 'due_diligence'), (4, 'financial_risk_management'), (5, 'legal_status'), (6, 'document_internal'), (7, 'document_external'), (8, 'sanction_check')]),
        ),
    ]
