# Generated by Django 3.0 on 2021-06-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20210601_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
