# Generated by Django 3.0 on 2021-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_userdiamondsponsor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
