# Generated by Django 3.0 on 2022-11-24 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_supplier_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_established_since',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
        ),
        migrations.AlterField(
            model_name='supplierflashsale',
            name='sku_number',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='supplierflashsale',
            unique_together={('sku_number', 'user_supplier')},
        ),
    ]
