# Generated by Django 3.0 on 2023-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20230105_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierflashsale',
            name='click_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierflashsale',
            name='reach_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdiamondsponsor',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
