# Generated by Django 3.0 on 2023-03-13 07:16

import apps.users.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_promotion_apply_scope'),
        ('users', '0036_userdiamondsponsor_reach_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_number', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(default='', max_length=2048)),
                ('type', models.CharField(choices=[('product', 'Product'), ('flash_sale', 'Flash_sale')], default='product', max_length=32)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_visibility', models.BooleanField(default=True)),
                ('confirmed_status', models.CharField(blank=True, choices=[('approved', 'Approved'), ('waiting', 'Waiting'), ('rejected', 'Rejected')], default='waiting', max_length=32, null=True)),
                ('specification', models.TextField(default='', max_length=2048)),
                ('minimum_order_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory_status', models.CharField(blank=True, choices=[('stocking', 'Stocking'), ('out_of_stock', 'Out_of_stock')], default='stocking', max_length=32, null=True)),
                ('provide_ability', models.CharField(blank=True, max_length=255, null=True)),
                ('support', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('origin_of_production', models.CharField(blank=True, max_length=255, null=True)),
                ('guarantee', models.CharField(blank=True, max_length=255, null=True)),
                ('other_information', models.CharField(blank=True, max_length=1024, null=True)),
                ('reach_number', models.IntegerField(default=0)),
                ('click_number', models.IntegerField(default=0)),
                ('url_path', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='master_data.PaymentTerm')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='master_data.UnitofMeasure')),
                ('user_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='users.Supplier')),
            ],
            options={
                'db_table': 'users_supplier_product',
                'unique_together': {('sku_number', 'user_supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProductWholesalePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_from', models.FloatField(blank=True, null=True)),
                ('quality_to', models.FloatField(blank=True, null=True)),
                ('price_bracket', models.FloatField(blank=True, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wholesale_price_list', to='users.SupplierProduct')),
            ],
            options={
                'db_table': 'users_supplier_product_wholesale_price',
            },
        ),
        migrations.CreateModel(
            name='SupplierProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to=apps.users.models.products_directory_path)),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='users.SupplierProduct')),
            ],
            options={
                'db_table': 'users_supplier_product_image',
            },
        ),
        migrations.CreateModel(
            name='SupplierProductFlashSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_flash_sales', to='users.SupplierProduct')),
            ],
            options={
                'db_table': 'users_supplier_product_flash_sale',
            },
        ),
        migrations.CreateModel(
            name='SupplierCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(max_length=500, upload_to=apps.users.models.supplier_certificate_path)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('csv', 'Csv'), ('doc', 'Doc'), ('image', 'Image'), ('video', 'Video'), ('other', 'Other')], max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('user_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='users.Supplier')),
            ],
            options={
                'db_table': 'users_supplier_certificate',
            },
        ),
        migrations.CreateModel(
            name='RelatedSupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_supplier_product_related_product', to='users.SupplierProduct')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_supplier_product_product', to='users.SupplierProduct')),
            ],
            options={
                'db_table': 'users_supplier_related_supplier_product',
            },
        ),
    ]
