# Generated by Django 3.0 on 2023-03-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_promotion_apply_scope'),
        ('users', '0037_relatedsupplierproduct_suppliercertificate_supplierproduct_supplierproductflashsale_supplierproducti'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product_category_list', to='master_data.Category')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product_category_list', to='users.SupplierProduct')),
            ],
            options={
                'db_table': 'users_supplier_supplier_product_category',
                'unique_together': {('category', 'supplier_product')},
            },
        ),
    ]
