# Generated by Django 3.0 on 2023-03-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_supplierproductcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='click_number',
            field=models.IntegerField(default=0),
        ),
    ]
