# Generated by Django 3.0 on 2023-03-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_userdiamondsponsor_click_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliersicp',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
