# Generated by Django 3.0 on 2023-05-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_suppliersicp_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='confirmed_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('approved', 'Approved'), ('waiting', 'Waiting'), ('rejected', 'Rejected')], default='waiting', max_length=32, null=True),
        ),
    ]
