# Generated by Django 3.0 on 2023-05-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_promotion_apply_scope'),
        ('users', '0041_auto_20230505_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='origin_of_production_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='master_data.Country'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='other_information',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
