# Generated by Django 3.0 on 2023-06-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20230515_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiamondsponsor',
            name='reach_number_count',
            field=models.IntegerField(default=0),
        ),
    ]
