# Generated by Django 3.1.5 on 2023-09-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20230602_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_referral_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
