# Generated by Django 3.1.5 on 2023-10-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_countrystate_countrystatetranslation'),
        ('users', '0045_supplier_company_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='company_country_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.countrystate'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_country_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.countrystate'),
        ),
    ]
