# Generated by Django 3.1.5 on 2023-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20231002_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='company_referral_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
