# Generated by Django 3.1.5 on 2023-10-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20231003_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductwholesaleprice',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproductwholesaleprice',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
