# Generated by Django 3.1.5 on 2023-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20231015_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='specification',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
