# Generated by Django 3.1.5 on 2023-10-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20231015_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductwholesaleprice',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
