# Generated by Django 3.1.5 on 2023-10-23 16:26

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20231022_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.banner_directory_path),
        ),
    ]
