# Generated by Django 3.1.5 on 2023-11-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_supplier_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='company_referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
