# Generated by Django 3.1.5 on 2023-11-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20231105_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproductwholesaleprice',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='supplierproductwholesaleprice',
            name='weight',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
