# Generated by Django 3.1.5 on 2023-11-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20231106_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='size',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
