# Generated by Django 3.0 on 2024-03-04 06:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_auto_20240303_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_established_since',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_status', models.CharField(choices=[('following', 'FOLLOWING'), ('un_follow', 'UN_FOLLOW')], default='un_follow', max_length=32)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower', to='users.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_following',
            },
        ),
    ]
