# Generated by Django 3.0 on 2024-05-05 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20240304_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowingSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_status', models.CharField(choices=[('following', 'FOLLOWING'), ('un_follow', 'UN_FOLLOW')], default='un_follow', max_length=32)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_supplier', to='users.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following_supplier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_following_supplier',
                'unique_together': {('user', 'supplier')},
            },
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
