# Generated by Django 3.0 on 2024-05-12 11:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20240505_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRatingSupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('delivery_time_rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product', to='users.SupplierProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating_supplier_product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_rating_product',
                'unique_together': {('user', 'supplier_product')},
            },
        ),
    ]
