# Generated by Django 3.0 on 2024-05-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_userratingsupplierproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userratingsupplierproduct',
            table='users_rating_supplier_product',
        ),
    ]
