# Generated by Django 3.0 on 2024-08-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_voucher_vouchertranslation'),
        ('users', '0059_auto_20240512_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_data.Currency'),
            preserve_default=False,
        ),
    ]
