# Generated by Django 3.0 on 2024-08-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_voucher_vouchertranslation'),
        ('users', '0060_supplierproduct_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='certification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='country',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, related_name='product_country', to='master_data.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='discountProgramForm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='green_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='official_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='regular_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='state',
            field=models.ForeignKey(default=730, on_delete=django.db.models.deletion.CASCADE, related_name='product_state', to='master_data.CountryState'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='status',
            field=models.CharField(default='trang thai', max_length=32),
            preserve_default=False,
        ),
    ]
