# Generated by Django 3.0 on 2024-08-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20240828_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='discountProgramForm',
            new_name='discount_program_form',
        ),
    ]
