# Generated by Django 3.0 on 2024-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_supplierproduct_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='picture',
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.IntegerField(choices=[(1, 'Trưởng khoa'), (2, 'Giáo vụ'), (3, 'Giảng viên')], default=3),
        ),
    ]
