# Generated by Django 3.0 on 2024-11-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20241114_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'master'), (2, 'a1'), (3, 'a2'), (4, 'a3')], null=True),
        ),
    ]
