# Generated by Django 3.0 on 2024-12-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20241114_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='bac_dao_tao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='khoa_hoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='loai_hinh_dao_tao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='lop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='mssv',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='nganh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='ngaysinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='noisinh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
