# Generated by Django 3.0 on 2024-11-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20241114_2340'),
        ('users', '0065_user_role'),
    ]

    operations = [
    ]
