# Generated by Django 3.0 on 2024-12-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20241201_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
