# Generated by Django 3.0 on 2024-12-01 07:07

import apps.users.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_delete_group'),
        ('users', '0067_auto_20241201_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='company_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_city',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_country_state',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.CountryState'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_number_of_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.NumberofEmployee'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_tax',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='company_website',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='valid_from',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='valid_to',
            field=models.DateTimeField(blank=True, default=apps.users.models.one_year, null=True),
        ),
    ]
