# Generated by Django 3.0 on 2024-12-01 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_delete_group'),
        ('users', '0068_auto_20241201_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.Position'),
        ),
    ]
