# Generated by Django 3.0 on 2024-12-01 07:14

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20241201_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.picture_directory_path),
        ),
    ]
