# Generated by Django 3.0 on 2024-12-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_user_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='noisinh',
            new_name='noi_sinh',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ngaysinh',
        ),
        migrations.AddField(
            model_name='user',
            name='ngay_sinh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
