# Generated by Django 3.0 on 2024-12-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20241201_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='ngaysinh',
            new_name='ngay_sinh',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='noisinh',
            new_name='noi_sinh',
        ),
    ]
