# Generated by Django 3.0 on 2024-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_auto_20241201_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
