# Generated by Django 3.0 on 2024-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20241202_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.IntegerField(choices=[(1, 'Trưởng khoa'), (2, 'Giáo vụ'), (3, 'Giảng viên'), (4, 'Trưởng bộ môn')], default=3),
        ),
    ]
