# Generated by Django 3.0 on 2024-12-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20241206_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='long_name',
            new_name='short_name',
        ),
    ]
