# Generated by Django 3.0 on 2024-12-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_auto_20241211_0251'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyer',
            table='users_student',
        ),
    ]
