# Generated by Django 3.0 on 2024-08-25 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('KCS', 'KCS'), ('WARRANTY', 'WARRANTY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderaddresses',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_addresses', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='orderpaymentdetails',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_details', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='orderpaymentdetails',
            name='payment_method',
            field=models.CharField(choices=[(1, 'Wallet'), (2, 'BankTransfer'), (3, 'OnePay')], max_length=20),
        ),
    ]
