# Generated by Django 3.0 on 2024-08-25 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20240512_1857'),
        ('order', '0004_order_onsignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=540, on_delete=django.db.models.deletion.CASCADE, related_name='order_buyer', to='users.Buyer'),
            preserve_default=False,
        ),
    ]
