# Generated by Django 3.0 on 2024-08-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_voucher_vouchertranslation'),
        ('order', '0005_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='master_data.Currency'),
            preserve_default=False,
        ),
    ]
