# Generated by Django 3.0 on 2024-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentdetails',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Wallet'), (2, 'BankTransfer'), (3, 'OnePay')], max_length=20),
        ),
    ]
