# Generated by Django 3.0 on 2024-08-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20240827_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taxCode',
            new_name='tax_code',
        ),
    ]
