# Generated by Django 3.0 on 2024-08-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('master_data', '0017_voucher_vouchertranslation'),
        ('order', '0009_auto_20240827_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_fee',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderaddresses',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderaddresses',
            name='district',
        ),
        migrations.RemoveField(
            model_name='orderaddresses',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddresses',
            name='country',
            field=models.OneToOneField(default=10000, on_delete=django.db.models.deletion.CASCADE, related_name='order_country', to='master_data.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddresses',
            name='state',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_state', to='master_data.CountryState'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderDeliveryShippingFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_shipping_fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_shipping_fee', to='delivery.ShippingFee')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_shipping_fee', to='order.Order')),
            ],
            options={
                'db_table': 'order_delivery_shipping_fee',
            },
        ),
    ]
