# Generated by Django 3.0 on 2024-09-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20240827_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPaymentDetails',
        ),
    ]
