# Generated by Django 3.0 on 2024-10-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_auto_20241006_2359'),
        ('order', '0011_delete_orderpaymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_code_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.Voucher'),
        ),
    ]
