# Generated by Django 3.0 on 2024-10-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_supplierproduct_certification'),
        ('order', '0012_order_voucher_code_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Buyer'),
        ),
    ]
