# Generated by Django 3.0 on 2024-10-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0019_auto_20241006_2359'),
        ('order', '0013_order_buyer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='supplier_product',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='buyer_Order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guaranteed_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='onsignee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_city', to='master_data.CountryState'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CART', 'Cart'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CART', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('KCS', 'Kcs'), ('WARRANTY', 'Warranty')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='taxGTGT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
