# Generated by Django 3.0 on 2024-10-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_supplierproduct_certification'),
        ('order', '0015_order_totalamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_supplier', to='users.Supplier'),
        ),
    ]
