# Generated by Django 3.0 on 2024-10-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('student', 'Sinh Viên'), ('lecturer', 'Giảng Viên'), ('admin_officer', 'Giáo Vụ'), ('dean', 'Trưởng Khoa')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'login_qlda',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CART', 'Cart'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('DELIVERING', 'Delivering'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CART', max_length=10),
        ),
    ]
