# Generated by Django 3.0 on 2024-10-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_login_emaillogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
