# Generated by Django 3.0 on 2024-10-21 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0019_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_giang_vien', models.CharField(max_length=255)),
                ('detai', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'giang_vien',
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=255)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='order.GiangVien')),
                ('members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_student_QLDA',
            },
        ),
    ]
