# Generated by Django 3.0 on 2024-10-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_supplierproduct_certification'),
        ('order', '0020_giangvien_groupstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='members',
            field=models.ManyToManyField(related_name='group_members', to='users.Buyer'),
        ),
    ]
