# Generated by Django 3.0 on 2024-10-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_supplierproduct_certification'),
        ('order', '0021_auto_20241022_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupstudent',
            name='members',
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='members',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_members_QLDA', to='users.Buyer'),
        ),
    ]
