from django.db import models
class RFXError(models.TextChoices):
    RFX_01 = "Invalid token"
    RFX_02 = "No permission"
    RFX_03 = "You are just able to invite at most 3 suppliers"
    RFX_04 = "The privious quote was considered as your final quote"
    RFX_05 = "The number of participants is enough"
    RFX_06 = "You cann't submit the quotation because you have not joined this RFX"
    RFX_07 = "The RFX has been expired" 
    RFX_08 = "The VAT tax must be in range of 0 and 100 percent"
    RFX_09 = "This RFX already moved to another round"
    RFX_10 = "Total percentatage of each item must be equal to 100"
    RFX_11 = "Informations is required"
    RFX_12 = "Proposals is required"
    RFX_13 = "Unit Price is required"
    RFX_14 = "VAT Tax is required"
    RFX_15 = "RFX does not exists"
    RFX_16 = "You can't confirm the quotation because you have not awarded this RFX"
    RFX_17 = "You confirmed this RFX"
    RFX_18 = "Supplier must be choose"