# Generated by Django 3.0 on 2021-06-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfx',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='rfx',
            name='quote_status',
        ),
    ]
