# Generated by Django 3.0 on 2021-06-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0002_auto_20210621_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfx',
            name='item_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfx',
            name='quote_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'full'), (2, 'not full')], default=2),
        ),
    ]
