# Generated by Django 3.0 on 2021-06-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0003_auto_20210621_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfxitemsupplier',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='rfxitemsupplier',
            name='confirm_price',
        ),
        migrations.AddField(
            model_name='rfxitemsupplier',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='note_for_buyer',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='rfxitem',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
