# Generated by Django 3.0 on 2021-06-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0004_auto_20210622_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfx',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
