# Generated by Django 3.0 on 2021-06-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0005_rfx_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
    ]
