# Generated by Django 3.0 on 2021-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0006_rfxsupplier_is_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfx',
            name='seat_available',
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='seat_available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'available'), (2, 'full')], default=1),
        ),
    ]
