# Generated by Django 3.0 on 2021-06-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0007_auto_20210625_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfxsupplier',
            name='awarded',
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='commercial_terms',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'accepted'), (2, 'rejected')], null=True),
        ),
    ]
