# Generated by Django 3.0 on 2021-06-28 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfx', '0008_auto_20210628_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFXAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rfx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_awards', to='rfx.RFX')),
                ('rfx_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_awarded_items', to='rfx.RFXItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfx_awarded_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rfx_award',
            },
        ),
    ]
