# Generated by Django 3.0 on 2021-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0011_rfxautonego'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxautonego',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
