# Generated by Django 3.0 on 2021-07-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0012_rfxautonego_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxsupplier',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
    ]
