# Generated by Django 3.0 on 2021-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0013_rfxsupplier_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfx',
            name='email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
