# Generated by Django 3.0 on 2021-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0014_rfx_email_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfx',
            name='is_send',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
