# Generated by Django 3.0 on 2021-07-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0015_rfx_is_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_joined',
            field=models.BooleanField(default=False),
        ),
    ]
