# Generated by Django 3.0 on 2021-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0016_rfxsupplier_is_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxattachment',
            name='attachmet_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'internal'), (2, 'external')], default=2),
        ),
    ]
