# Generated by Django 3.0 on 2021-08-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0017_rfxattachment_attachmet_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfxattachment',
            old_name='attachmet_type',
            new_name='attachment_type',
        ),
    ]
