# Generated by Django 3.0 on 2021-08-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0018_auto_20210810_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxattachment',
            name='upload_by',
            field=models.PositiveSmallIntegerField(choices=[(1, 'buyer'), (2, 'supplier')], default=1),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_delivery_address_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_delivery_term_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_other_requirements_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_payment_term_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_terms_conditions_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='rjected_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
