# Generated by Django 3.0 on 2021-08-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0019_auto_20210811_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfxsupplier',
            old_name='rjected_reason',
            new_name='payment_term_rjected_reason',
        ),
    ]
