# Generated by Django 3.0 on 2021-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0020_auto_20210811_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxsupplier',
            name='delivery_address_rjected_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='delivery_term_rjected_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='other_requirements_rjected_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='terms_conditions_rjected_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
