# Generated by Django 3.0 on 2021-08-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0022_auto_20210817_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfxitemsupplier',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='rfx',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfxitemsupplier',
            name='informations',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='rfxitemsupplier',
            name='proposals',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='rfxsupplier',
            name='commercial_terms',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
