# Generated by Django 3.0 on 2021-08-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0023_auto_20210817_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfx',
            name='is_full',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
