# Generated by Django 3.0 on 2021-08-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0024_rfx_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfx',
            name='time_view_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
