# Generated by Django 3.0 on 2021-08-30 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_promotion_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfx', '0025_rfx_time_view_minutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RFX',
            new_name='RFXData',
        ),
    ]
