# Generated by Django 3.0 on 2021-08-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0026_auto_20210830_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxitemsupplier',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rfxitemsupplier',
            name='vat_tax',
            field=models.FloatField(default=0),
        ),
    ]
