# Generated by Django 3.0 on 2021-09-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0027_auto_20210831_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxaward',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
