# Generated by Django 3.0 on 2021-09-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0028_rfxaward_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxdata',
            name='auto_negotiation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
