# Generated by Django 3.0 on 2021-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0029_rfxdata_auto_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_best_price',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
