# Generated by Django 3.0 on 2021-09-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0031_rfxitemsupplier_submitted_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RFXAutoNego',
        ),
    ]
