# Generated by Django 3.0 on 2021-10-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0032_delete_rfxautonego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfxitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
