# Generated by Django 3.0 on 2021-10-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0033_auto_20211004_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfxitemsupplier',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rfxitemsupplier',
            name='vat_tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
