# Generated by Django 3.0 on 2023-01-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_promotion_commission'),
        ('rfx', '0035_rfxattachment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfxdata',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='master_data.Category'),
        ),
    ]
