# Generated by Django 3.0 on 2023-02-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0036_auto_20230109_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxsupplier',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rfxdata',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'draft'), (2, 'published'), (3, 'due date expire'), (4, 'awarded'), (5, 'e-auction'), (6, 'negotiation'), (7, 'completed'), (8, 'cancelled'), (9, 'confirmed')], default=1),
        ),
    ]
