# Generated by Django 3.1.5 on 2023-10-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0015_countrystate_countrystatetranslation'),
        ('rfx', '0038_rfxitemsupplier_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfxdata',
            name='country',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='master_data.country'),
        ),
        migrations.AddField(
            model_name='rfxdata',
            name='country_state',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_state', to='master_data.countrystate'),
        ),
    ]
