# Generated by Django 3.1.5 on 2023-11-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfx', '0039_auto_20231005_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfxdata',
            name='rfx_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'RFI'), (2, 'RFP'), (3, 'RFQ'), (4, 'PO')]),
        ),
    ]
